name: todos
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  path_provider: ^2.1.5
  errors:
    path: ../errors
  network_info:
    path: ../network_info
  freezed_annotation: ^2.4.4
  # json_annotation: ^4.8.0
  json_annotation: ^4.9.0
  fpdart:  
  sqflite:
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  flutter_bloc: ^8.1.6
  dio:
  http:  
  connectivity_plus: ^6.1.0
  # connectivity_plus: ^3.0.3
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  isar_generator: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0


