name: network_info
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4
  # sdk: '>=2.19.4 <3.0.0'

dependencies:
  #path: ^1.8.0
  # connectivity_plus: ^3.0.3
  connectivity_plus: ^6.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
