name: errors
description: Dart package which manages app common errors.
version: 1.0.0

environment:
  sdk: ^3.5.4
  # sdk: '>=2.19.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  meta: ^1.8.0
  very_good_analysis: ^6.0.0
